[pytest]
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
    property_test: marks tests as property-based tests

testpaths = tests
norecursedirs = cdk.out .venv build dist *.egg-info infra/cdk.out
