# Copyright (c) 2026 Amazon Web Services
# Licensed under the MIT-0 License
# See LICENSE file in the project root for full license information.
# Security scan: See security/SCAN_PROCESS.md for scan results and attestation.
# Risk assessment: See security/SECURITY.md for threat model and risk documentation.

"""Shared data models for the routing configuration pipeline."""

from __future__ import annotations

from typing_extensions import TypedDict


class RoutingJson(TypedDict):
    """Structured routing configuration generated by Bedrock."""
    by_service: dict[str, str]  # service name → Jira assignee account ID
    by_ou: dict[str, str]       # OU name/path → Jira assignee account ID
    default: str                 # fallback Jira assignee account ID


class SlackInteractivePayload(TypedDict):
    """Parsed Slack interactive message payload."""
    type: str                    # "interactive_message"
    callback_id: str             # encoded routing context
    actions: list[dict]          # [{"name": "approve"|"reject", "value": "..."}]
    user: dict                   # {"id": "...", "name": "..."}
    token: str                   # Slack verification token (deprecated, use signature)


class RoutingReviewMessage(TypedDict):
    """Data needed to construct the Slack review message."""
    source_file: str             # original S3 object key
    routing_json: RoutingJson    # generated routing config
    service_count: int           # len(by_service)
    ou_count: int                # len(by_ou)
    default_assignee: str        # default value


class SecretPayload(TypedDict, total=False):
    """Shape of the Jira secret in Secrets Manager.
    total=False because not all keys are always present."""
    jira_api_token: str
    service_team_map: dict[str, str]
    ou_team_map: dict[str, str]
    default_assignee: str
